version: "3.8"

services:
  frontend:
    container_name: ts-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend:/app/"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - application

  backend:
    restart: always
    container_name: ts-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    networks:
      - application

  database:
    restart: always
    container_name: ts-database
    image: mariadb:10.5.12
    environment:
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - 3306
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    networks:
      - application

networks:
  application:
