version: "3.8"

services:
  frontend:
    container_name: ts-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend:/app/"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: ts-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
