version: "3.8"

services:
  frontend:
    restart: always
    container_name: st-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app/"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - application

  web-customer:
    restart: always
    container_name: web-customer
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - application

  api-customer:
    restart: always
    container_name: api-customer
    build:
      context: ./backend/customer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "mariadb"
    networks:
      - application
    volumes:
      - "./data/images:/app/images"

  mariadb:
    restart: always
    container_name: mariadb
    image: mariadb:10.5.12
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - TZ=Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - "./data/mariadb:/var/lib/mysql"
      - "./config/mariadb:/docker-entrypoint-initdb.d"
    networks:
      - application

  redis:
    restart: always
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./config/redis/redis.conf:/redis.conf
    command: redis-server /redis.conf
    networks:
      - application

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - application
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=password

networks:
  application: null
