version: "3.8"

services:
  frontend:
    restart: always
    container_name: st-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - application

  backend:
    restart: always
    container_name: st-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    networks:
      - application

  database:
    restart: always
    container_name: st-database
    image: mariadb:10.5.12
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - TZ=Asia/Bangkok
    ports:
      - 3306
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    networks:
      - application

networks:
  application:
