version: "3.8"

services:
  frontend:
    restart: always
    container_name: st-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app/"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - application

  backend:
    restart: always
    container_name: st-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    networks:
      - application

  database:
    restart: always
    container_name: st-database
    image: mariadb:10.5.12
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - TZ=Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - "/app/shoptree/database:/var/lib/mysql"
      - "./database:/docker-entrypoint-initdb.d"
    networks:
      - application

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - application
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=password

networks:
  application:
